version: "3.7"

services:
  saturn3sample-django:
    volumes:
      - ./logs:/logs
      - ./backend:/backend
      - ./dash_app_2:/dash_app_2
      - ./manage.py:/manage.py:ro
      - ./requirements.txt:/requirements.txt
      - ./env:/env
      - ./CHANGELOG.md:/CHANGELOG.md:ro
      - /etc/localtime:/etc/localtime:rw
