# version: "3"

services:
  saturn3sample-django:
    restart: unless-stopped
    build: .
    ports:
      - "127.0.0.1:8080:8080"
      - "3000"
    tty: true
    depends_on:
      db:
        condition: service_healthy
    command: >
      /bin/sh -c "
      python manage.py makemigrations gui;
      python manage.py migrate gui;
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py collectstatic --noinput;
      python manage.py runserver 0.0.0.0:8080
      "

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - path: env/development.env
        required: true
      - path: env/production.env
        required: false
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d saturn3samples" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 127.0.0.1:5432:5432
