"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pydantic_settings import BaseSettings, SettingsConfigDict
from typing import Optional
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file() -> str:
    output = ""
    env_dir = "env"
    dev_path = os.path.join(env_dir, "development.env")
    prod_path = os.path.join(env_dir, "production.env")

    if os.path.exists(prod_path):
        output = prod_path

    else:
        output = dev_path

    return output


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=load_env_file())

    POSTGRES_PASSWORD: str
    POSTGRES_USER: str
    POSTGRES_DB: str
    DJANGO_SECRET_KEY: str
    DJANGO_DEBUG: bool
    CSFR_COOKIE_SECURE: bool
    SESSION_COOKIE_SECURE: bool
    EMAIL_BASE_URL: str
    MAPPLOT_TOKEN: Optional[str] = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SETTINGS = Settings()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SETTINGS.DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = SETTINGS.DJANGO_DEBUG

ALLOWED_HOSTS = [
    "0.0.0.0",
    "saturn3sample-django",
    "localhost",
    "ibsm-saturn3.uniklinik-freiburg.de",
    "saturn3.uniklinik-freiburg.de"
]
CSRF_TRUSTED_ORIGINS = [
    "http://0.0.0.0",
    "https://ibsm-saturn3.uniklinik-freiburg.de",
    "https://saturn3.uniklinik-freiburg.de",
]

CSRF_COOKIE_SECURE = SETTINGS.CSFR_COOKIE_SECURE
SESSION_COOKIE_SECURE = SETTINGS.SESSION_COOKIE_SECURE

# Cookie options for automatic logout
SESSION_COOKIE_AGE = 900
SESSION_SAVE_EVERY_REQUEST = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "backend.gui",
    "tempus_dominus",
    'markdownify.apps.MarkdownifyConfig',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'bootstrap4',
    'dpd_static_support',
]

TEMPUS_DOMINUS_DATE_FORMAT = "YYYY-MM-DD"
DATE_FORMAT = "Y-m-d"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    # dash
    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["backend/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": SETTINGS.POSTGRES_DB,
        "USER": SETTINGS.POSTGRES_USER,
        "PASSWORD": SETTINGS.POSTGRES_PASSWORD,
        "HOST": "db",  # set in docker-compose.yml
        "PORT": "5432",  # default postgres port
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "backend", "static/")
STATIC_URL = "static/"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_DIRS = (os.path.join(BASE_DIR, "backend", "gui", "static"),)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]
LOGIN_URL = "/login/"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "audit": {
            "format": "{asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "audit_log": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "audit.log"),
            "maxBytes": 500 * 1024 ** 2,  # 500MB
            "backupCount": 2,
            "formatter": "audit",
        },
    },
    "loggers": {
        "s3sample": {
            "handlers": ["audit_log"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

# Mail server settings

EMAIL_HOST = "smtp.uniklinik-freiburg.de"
EMAIL_HOST_USER = "saturn3@uniklinik-freiburg.de"
EMAIL_ACCOUNT_CREATION_PATH = "reset"
EMAIL_BASE_URL = SETTINGS.EMAIL_BASE_URL
EMAIL_PORT = 25
EMAIL_SUBJECT_PREFIX = "[SATURN3 SAMPLE TRACKING] "
MARKDOWNIFY = {
    "default": {
        "WHITELIST_TAGS": [
            'a',
            'abbr',
            'acronym',
            'b',
            'blockquote',
            'em',
            'h1',
            'h2',
            'h3',
            'h4',
            'h5',
            'h6',
            'i',
            'li',
            'ol',
            'p',
            'strong',
            'ul',
            'hr'
        ]
    }
}

# DASH
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Staticfiles finders for locating dash app assets and related files

STATICFILES_FINDERS = [

    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',

    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django_plotly_dash.finders.DashAppDirectoryFinder',
]


# Plotly components containing static content that should
# be handled by the Django staticfiles infrastructure

PLOTLY_COMPONENTS = [

    # Common components (ie within dash itself) are automatically added

    # django-plotly-dash components
    'dpd_components',
    # static support if serving local assets
    'dpd_static_support',

    # Other components, as needed
    'dash_bootstrap_components',
    'dash_ag_grid',
]



# DASH END

FILE_TRACEBACK_DIR = "/tmp"
DATA_UPLOAD_MAX_MEMORY_SIZE = 2000000000
# PASSWORD_RESET_TIMEOUT = 

PLOTLY_DASH = {
    "view_decorator": "django_plotly_dash.access.login_required",
    "serve_locally": True,
}
